# Generated by Django 2.2.6 on 2019-10-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20191024_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('P', 'primary'), ('I', 'info'), ('W', 'warning'), ('S', 'success'), ('DK', 'dark'), ('DR', 'danger')], default='P', max_length=2),
        ),
    ]
