# Generated by Django 2.2.6 on 2019-10-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('P', 'Blue'), ('I', 'Light Blue'), ('W', 'Yellow'), ('S', 'Green'), ('DK', 'Black'), ('SE', 'Gray'), ('DR', 'Red')], default='P', max_length=2),
        ),
    ]
