# Generated by Django 2.2.6 on 2019-11-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20191028_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='or_number',
            field=models.CharField(default=123455, max_length=20),
            preserve_default=False,
        ),
    ]
