# Generated by Django 2.2.6 on 2019-11-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_or_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_dine',
            field=models.BooleanField(default=True),
        ),
    ]
